inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/bin/*'
    - '*.gemspec'
    - 'vendor/bundle/**/*'
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
